# Generated by Django 4.2.7 on 2023-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_price_subscription_price_in_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
