# Generated by Django 4.2.7 on 2023-12-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="does_email_receive",
            field=models.BooleanField(default=True),
        ),
    ]
