# Generated by Django 4.2.7 on 2024-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_does_email_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
