# Generated by Django 4.2.7 on 2023-11-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectRequestCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=35)),
                ("request_count", models.IntegerField(default=0)),
                ("last_request_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
