# Generated by Django 4.2.7 on 2023-11-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("front", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredUserWordCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("word_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="detectrequestcounter",
            name="ip_address",
            field=models.CharField(max_length=45),
        ),
    ]
