# Generated by Django 4.2.7 on 2023-11-28 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="document_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
