# Generated by Django 4.2.7 on 2023-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='readibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
