# Generated by Django 4.2.7 on 2023-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_emailcampaign_recipients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="recipients",
            field=models.JSONField(null=True),
        ),
    ]
