# Generated by Django 4.2.7 on 2023-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_emailcampaign_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subscrioption_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('enterprise', 'Enterprise'), ('free', 'Free'), ('all', 'all')], max_length=10, null=True),
        ),
    ]
